// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
	export interface GlobalComponents {
		AButton: typeof import("ant-design-vue/es")["Button"];
		StaticFile: typeof import("./src/components/StaticFile/index.vue")["default"];
		SvgIcon: typeof import("./src/components/SvgIcon/index.vue")["default"];
	}
}

export {};
